name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Update version patch in pom.xml
      id: versioning
      run: |
        version_file=pom.xml
        old_version=$(grep -m1 "<version>" $version_file | sed -E 's/.*<version>(.*)<\/version>.*/\1/')
        base_version=${old_version%.*}
        patch=$((${old_version##*.} + 1))
        new_version="${base_version}.${patch}"
        sed -i "s|<version>$old_version</version>|<version>$new_version</version>|" $version_file
        echo "version=$new_version" >> $GITHUB_OUTPUT

    - name: Commit and push new version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add pom.xml
        git commit -m "chore: bump version to ${{ steps.versioning.outputs.version }}"
        git push origin HEAD:${{ github.ref_name }}

    - name: Docker build (multi-stage)
      run: |
        docker build -t myapp:${{ steps.versioning.outputs.version }} .

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to DockerHub
      run: |
        docker tag myapp:${{ steps.versioning.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.versioning.outputs.version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.versioning.outputs.version }}
